name: Run main

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.11
        
        - name: Install dependencies
          run: pip install -U selenium

        - name: Run main
          run: python main.py